application: airsoft
version: 1
runtime: python27
api_version: 1
threadsafe: True

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static/images
  static_dir: static/images

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: main.app

builtins:
- remote_api: on
- appstats: on
